- type: entity
  parent: MCStructure
  id: MCComputerIndestructible
  abstract: true
  components:
  - type: Sprite
    sprite: _MC/Structures/Machines/computer.rsi
    drawdepth: SmallObjects
  - type: Corrodible
    isCorrodible: false
  - type: InteractionOutline
